### ISSUE TITLE
Add a function to force datadr to persist transformations immediately

### ISSUE THREAD

**Issue by amwhite** [tesseradata/datadr#58]
Enhancement request: a function that would force a transformation function to be calculated and persisted immediately, rather than waiting until `recombine` or one of the other functions is called. 

Note: if/when you do this, remove the comment I added to the `addTransform` documentation that shows the workaround of calling `recombine(dat, combDdo, output = …)`.

**Comment by hafen** [comment]
This is a long-needed function.  I will add it.  Should be simple.  I think we'll call it `persist()`.

**Comment by hafen** [comment]
Fixed.  Called it `drPersist()`
