### ISSUE TITLE
Simplify function return requirements for a key/value transformation

### ISSUE THREAD

**Issue by hafen** [tesseradata/datadr#60]
This may break some old analysis code, but after a lot of thought I think the current approach of how to apply transformations to functions is a bit unnatural.  To review, the current approach is:

- A transformation function with one argument will be given the value of a key/value pair and should also return a value
- A transformation function with two arguments will be given the key and the value and needs to return a key/value pair

The reason this logic exists is that usually the user wants to operate on just the value, and we want to make that as simple as possible.  But we also want to be able to get information from the key if needed.  But what I have found is that almost every transformation I apply that needs the key, I still only want to return a value (I'm not doing anything to the key - just getting information from it), so having to return a key-value pair is a bit cumbersome.  Therefore, I'm proposing the following change to the logic:

- A transformation with a single argument gets a value and with two arguments gets the key and the value, but it is always expected that the transformation returns just a value.
- The only case where the result of a transformation function will be treated as a key/value pair instead of just a value is when the result of the function is explicitly of class "kvPair" (specified by the user by calling `kvPair()`.  Since this will occur so rarely, I think this is a good choice.

This will be simple to do and simple to adapt new code to, but may effect some old code of others.

@amwhite, I think this might effect you most.  What do you think?

**Comment by amwhite** [comment]
I think that makes sense and won't require too much work to fix past examples.

**Comment by hafen** [comment]
@amwhite note that I just updated this - please update any examples accordingly.  See here for an example: http://tessera.io/docs-datadr/#common_data_operations
