### ISSUE TITLE
as.list.key

### ISSUE THREAD

**Issue by jrounds** [tesseradata/datadr#77]
```
as.list.key = function(key){ 
	keys = strsplit(key,"|", fixed=TRUE)
	keys = unlist(lapply(keys, function(k) strsplit(unlist(k), "=", fixed=TRUE)), recursive = FALSE) # the need for the unlist is a mystery to me
	fid = lapply(keys, function(k) k[[1]])
	fv = lapply(keys, function(k) k[[2]])
	names(fv) = unlist(fid)
	return(fv)
	
}
```
I find myself using the above a lot on datadr keys.  Anything like this in datadr? (basically invert the paste code).

It is used like:
```
> k = ddo_local[[1]]$key
> k
[1] "DMISID=0001|year=2010"
> as.list.key(k)
$DMISID
[1] "0001"

$year
[1] "2010"
```

On a side note I was sitting around last night and amusing myself with a smirky thought.  You ever noticed that the "|" in the key is the logical "or" symbol in R?  It reads DMISID=0001 or year = 2010.  Shouldn't it be "&" =)

**Comment by hafen** [comment]
If you have a data set with keys such as this, it was probably created by divide, in which case there is an attribute stored with every value (in case you want to get keys from the value) that preserves the keys in the form that you are after.  There are functions that let you access these, for example:

```
getSplitVars(ddo_local[[1]]$value)
```

Or

```
getSplitVar(ddo_local[[1]]$value, "DMISID")
```


Indeed the `|` was not meant to mean "or", but a visual separator - sorry for the confusion :)

**Comment by jrounds** [comment]
Yeah, I think I need to use datadr more as it was intended.  

I like divide().  I like the usefulness of ddo(hdfsConn).  But other than those two things I been using mrExec a lot, and I use the as.list.key in maps of mrExec to make a new datadr-like-key.  

I think maybe what I need to do is present a workflow where I am doing that and maybe work out the "datadr way".

**Comment by hafen** [comment]
mrExec isn't a bad thing to use :).  But you get away with a lot of MapReduce-like operations with addTransform and recombine.  If you have some use cases you are curious about, hop on the mailing list and I'd be happy to talk through it.
