### ISSUE TITLE
stringi on windows 10 and error

### ISSUE THREAD

**Issue by hathawayj** [tesseradata/datadr#80]
devtools::install_github("tesseradata/datadr")
Downloading GitHub repo tesseradata/datadr@master
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘stringi’

When I tried installing stringi before it said that it was the wrong one.

**Comment by hafen** [comment]
stringi is the second-most downloaded R package: http://www.r-pkg.org.  If you are not able to install it I would guess it has something to do with your CRAN setup or your version of R.

**Comment by hafen** [comment]
Closing as I'm pretty sure this is an issue with your CRAN repo setting.
