### ISSUE TITLE
Ability to Handle csv.gz files stored into HDFS

### ISSUE THREAD

**Issue by bedantaguru** [tesseradata/datadr#92]
I have tested below code with local connection. Which works perfectly with gz files as read.csv or read.table does. However when I tried to replicate the same this in HDFS it did not work. 
This is working : 
```
# local disk
sampleDiskStore <- localDiskConn(file.path(tempdir(), "sample_submission"), autoYes = TRUE)

sampleDiskData <- drRead.csv("Data/sample_submission.csv.gz", rowsPerBlock = 20000, output = sampleDiskStore)

updateAttributes(sampleDiskData)
```
But when I tried uploading same data in HDFSand pointing to the folder that contains the gz it is not working. I think somehow I need to specify that the file is gz file but I could not do that 

```
rhdel("/user/ruser/DataDR/Test/Sample/RB")

sampleStore_RB<- hdfsConn(paste0(hdfs_root_path,"/Sample/RB"), autoYes = T)

# data in "/user/ruser/DataDR/Test/Raw"
# Thi will definitely not gonna work sampleData_RB <- drRead.csv(gzfile(hdfsConn(loc = "/user/ruser/DataDR/Test/RawZip", type = "text", autoYes = T)), rowsPerBlock = 20000, output = sampleStore_RB)
sampleData_RB <- drRead.csv(hdfsConn(loc = "/user/ruser/DataDR/Test/RawZip", 
                                     type = "text", autoYes = T), 
                            rowsPerBlock = 20000, 
                            output = sampleStore_RB)
sampleData_RB <- updateAttributes(sampleData_RB) # this is failing
```

[Note in above `/user/ruser/DataDR/Test/RawZip`  the only file present is sample_submission.csv.gz  and all paths are in HDFS]

Kindly tell me what would be the solution for the same.

**Comment by hafen** [comment]
Is it possible to use bz2 compression instead of gz?  gzip is not a splittable format in Hadoop but bz2 is.  I've used datadr/RHIPE with bz2 files pretty regularly, but haven't tried gz.

**Comment by bedantaguru** [comment]
.bz2 is working thanks
