### ISSUE TITLE
README link does not work.

### ISSUE THREAD

**Issue by mpancia** [tesseradata/datadr#98]
The link to http://tesseradata.github.io/docs-datadr/ on the main README page does not work.

**Comment by hafen** [comment]
Which README? I don't see this link.

**Comment by mpancia** [comment]
@hafen Sorry -- the one on the main page: https://github.com/delta-rho/datadr/blob/master/README.md

**Comment by hafen** [comment]
Oh I see - I was looking at the text of the README and didn't see the URL but it was redirecting for some reason. It should be fixed now. Thanks for pointing this out.
